# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Include openchami command vars
  ansible.builtin.include_vars: "{{ role_path }}/../../../common/vars/openchami_commands.yml"

- name: Include openchami vars
  ansible.builtin.include_vars: "{{ openchami_config_vars_path }}"

- name: Delete smd configuration
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/delete_smd_config.yml"

- name: Discover ochami nodes
  environment: "{{ hostvars['oim']['ochami_env'] | default({}) }}"
  block:
    - name: Discover ochami nodes
      ansible.builtin.command: "{{ openchami_cli_path }} {{ openchami_commands.smd_discover_static }}"
      changed_when: true
      register: openchami_discover
  rescue:
    - name: Failed to discover nodes
      ansible.builtin.debug:
        msg: "{{ discover_fail_msg }}. Error: {{ openchami_discover.stderr_lines }}"

- name: Verify node created in smd
  environment: "{{ hostvars['oim']['ochami_env'] | default({}) }}"
  ansible.builtin.shell: |
    set -o pipefail && \
    {{ openchami_cli_path }} {{ openchami_commands.smd_component_get_nodes }}
  changed_when: true
  register: openchami_smd_status

- name: Openchami smd status output
  ansible.builtin.debug:
    msg: "{{ openchami_smd_status.stdout_lines }}"
    verbosity: 2

- name: Load the openchami hostname.yaml
  ansible.builtin.template:
    src: "{{ openchami_hostname_template }}"
    dest: "{{ openchami_hostname_vars_path }}"
    mode: "{{ hostvars['localhost']['file_permissions_644'] }}"
  vars:
    nodes: "{{ hostvars['localhost']['read_mapping_file']['dict'] | dict2items }}"

- name: Configure the hostname
  environment: "{{ hostvars['oim']['ochami_env'] | default({}) }}"
  ansible.builtin.command: "{{ openchami_cli_path }} {{ openchami_commands.cloud_init_node_set }} @\"{{ openchami_hostname_vars_path }}\""
  changed_when: true
